version: '3'

services:
    caliper:
        container_name: caliper
        working_dir: /hyperledger/caliper/workspace
        image: hyperledger/caliper:0.5.0-unstable-20220324083316
        command: launch manager
        network_mode: host
        environment:
        - CALIPER_BIND_SUT=ethereum:latest
        - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml
        - CALIPER_NETWORKCONFIG=networks/networkconfig.json
        - CALIPER-FLOW-SKIP-INSTALL=true
        volumes:
        - ./caliper-benchmarks:/hyperledger/caliper/workspace