simpleArgs: &simple-args
  moneyToTransfer: &money-to-transfer 1
  numberOfAccounts: 1

test:
  name: erc20
  description: >-
    To benchmark the network transactions.
  workers:
    type: local
    number: 1
  rounds:
    - label: 4 txns with 1tps
      description: Transfering erc20 token between accounts.
      txNumber: 4
      rateControl:
        type: fixed-rate
        opts:
          tps: 1
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          <<: *simple-args
          money: *money-to-transfer
    - label: 100 txns with 10-100tps
      description: Transfering erc20 token between accounts.
      txNumber: 100
      rateControl:
        type: linear-rate
        opts:
          startingTps: 10
          finishingTps: 100
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          <<: *simple-args
          money: *money-to-transfer
    - label: 300 txns with 100-300tps
      description: Transfering erc20 token between accounts.
      txNumber: 500
      rateControl:
        type: linear-rate
        opts:
          startingTps: 100
          finishingTps: 300
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          <<: *simple-args
          money: *money-to-transfer
    - label: 1000 txns with 200-500tps
      description: Transfering erc20 token between accounts.
      txNumber: 1000
      rateControl:
        type: linear-rate
        opts:
          startingTps: 200
          finishingTps: 500
      workload:
        module: benchmarks/scenario/simple/transfer.js
        arguments:
          <<: *simple-args
          money: *money-to-transfer
